### PR TITLE
Fix: Ensure SIGTERM signal terminates lat_fifo benchmark child process

### LINKED ISSUE #2762: Benchmark `lmbench/fifo_lat` fails
### Describe the bug

The `lmbench/fifo_lat` benchmark fails, and results in continuous error message output that will eventually consume all available disk space on the self-hosted runner.

### To Reproduce

```
make run_kernel BENCHMARK=lmbench/fifo_lat
```

### Expected behavior

The benchmark completes execution and terminates properly.

### Logs

```
Running benchmark: lmbench/fifo_lat on asterinas
The VM is ready for the benchmark.
*** Running the LMbench fifo latency test ***
(w) read/write on pipe: No such file or directory
(w) read/write on pipe: Invalid argument
(w) read/write on pipe: Invalid argument
(w) read/write on pipe: Invalid argument
...
```

### PR DESCRIPTION
**Pull request by cqs21**
This could fix https://github.com/asterinas/asterinas/issues/2762, and the error occurs on both Asterinas and Linux systems.

### CODE REVIEW

File: src/lat_fifo.c [hunk 1]
```diff
@@ -88,6 +88,7 @@ initialize(iter_t iterations, void *cookie)
 	handle_scheduler(benchmp_childid(), 0, 1);
 	switch (state->pid = fork()) {
 	    case 0:
+		signal(SIGTERM, SIG_DFL);
```
Comment (tatetian) [inline src/lat_fifo.c]: But where sets the signal handler for `SIGTERM` to a non-default value?

Comment (cqs21) [reply src/lat_fifo.c]: It is set here: https://github.com/asterinas/lmbench/blob/25a43f544af396b81c7a378c83d33f2cbab10fcc/src/lib_timing.c#L222

And `benchmp_sigterm` cannot terminates the child process.
https://github.com/asterinas/lmbench/blob/25a43f544af396b81c7a378c83d33f2cbab10fcc/src/lib_timing.c#L93-L96

Comment (tatetian) [reply src/lat_fifo.c]: But surely, `signal(SIGTERM, benchmp_sigterm)` is called for a reason. Why is it ok to override it (blindly)? And since this problem is introduced in the common infra code of LMbench, I can't see why only one benchmark, `lat_fifo`, suffers from the problem. If the infra code is problematic, why not fix the infra code?

As a bugfix, you need to point out where the LMbench code goes wrong and justify why it should be fixed the way you do. Simply saying that doing this would make a problem in Asterinas disappear is insufficient.

Comment (cqs21) [reply src/lat_fifo.c]: > I can't see why only one benchmark, lat_fifo, suffers from the problem

Other benchmarks also implement similar handling.
https://github.com/asterinas/lmbench/blob/25a43f544af396b81c7a378c83d33f2cbab10fcc/src/lat_sem.c#L80-L85
https://github.com/asterinas/lmbench/blob/25a43f544af396b81c7a378c83d33f2cbab10fcc/src/lat_pipe.c#L83-L90
https://github.com/asterinas/lmbench/blob/25a43f544af396b81c7a378c83d33f2cbab10fcc/src/lat_unix.c#L94-L98

Comment (tatetian) [reply src/lat_fifo.c]: Ok. This is a much needed piece of information that should have been provided in the beginning.

Then the next question is which one of the two forms to choose? This one

```
signal(SIGTERM, exit); 
```

or this one

```
signal(SIGTERM, SIG_DFL); 
```

I don't think that they have any real differences. But semantically, the former one conveys the intention more clear.

Do you choose the latter for any particular reason? I can't find any occurrences of `signal(SIGTERM, SIG_DFL);` in the current codebase. If you do not have any particular reason to break the existing practice in the codebase, then you should following the established practice.

Comment (cqs21) [reply src/lat_fifo.c]: > Do you choose the latter for any particular reason?

No. While reviewing the `lat_fifo.c` code, I found that it doesn't exit properly when receiving `SIGTERM`, so I decided to reset the handler to default, without referencing other benchmark implementations yet. I also agree that the former is a better choice.

**Review by tatetian — COMMENTED** [review]
LGTM. Thanks for the contribution!
